### ISSUE TITLE
An error for this code: cor = sn.co.modules_to_annotation_cor(adata_r, net, figsize=(12,6), cor_method="spearman")

### ISSUE THREAD

**Issue by Leslie456456** [oubounyt/SCANet#6]
Hi, 

A nice job! I encountered a technical issue when I run this code: 
cor = sn.co.modules_to_annotation_cor(adata_r, net, figsize=(12,6), cor_method="spearman")
It shows such an error: 
Traceback (most recent call last):
  File "C:\Users\PycharmProjects\pythonProject\main.py", line 127, in <module>
    cor = sn.co.modules_to_annotation_cor(adata_r, net, figsize=(12,6), cor_method="spearman")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PycharmProjects\pythonProject\venv\Lib\site-packages\scanet\coexpression.py", line 197, in modules_to_annotation_cor
    MEtrait = module_to_annotation_cor_r(final_exp_, net, cor_method=cor_method)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PycharmProjects\pythonProject\venv\Lib\site-packages\rpy2\robjects\functions.py", line 208, in __call__
    return (super(SignatureTranslatedFunction, self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PycharmProjects\pythonProject\venv\Lib\site-packages\rpy2\robjects\functions.py", line 131, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PycharmProjects\pythonProject\venv\Lib\site-packages\rpy2\rinterface_lib\conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PycharmProjects\pythonProject\venv\Lib\site-packages\rpy2\rinterface.py", line 873, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in module_trait_cor(exp = final_exp, MEs = net$MEs, cor_method = cor_method,  : 
  unused arguments (cex.lab.x = 0.01, cex.lab.y = 0.01, cex.text = 0.01)

Could you provide some information about this error? Thank you!

**Comment by oubounyt** [comment]
please install the newest version
